# Generated by Django 3.2.6 on 2021-08-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_rename_nome_categoria_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='nome',
            new_name='titulo',
        ),
    ]
