# Generated by Django 3.2.6 on 2021-08-22 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_rename_nome_filme_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='titulo',
        ),
    ]
