# Generated by Django 3.2.6 on 2021-08-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_remove_filme_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='titulo',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
